create table hotel
(booking_id int, customer_id int, status char(30), check_in date, 
check_out date, no_of_rooms int, hotel_id int, amount int, discount int,
date_of_booking date);
select * from hotel;
describe hotel;
-- city --
create table city 
(hotel_id int, city char(20));
-- join two tables--
Create table OYOHOTEL as (SELECT hotel.booking_id, hotel.customer_id , hotel.status , hotel.check_in, 
hotel.check_out , hotel.no_of_rooms, hotel.hotel_id , hotel.amount, hotel.discount,
hotel.date_of_booking ,city.H_id, city.city
FROM hotel 
LEFT JOIN city
ON hotel.hotel_id = city.H_id);
Alter table city rename column hotel_id to H_id;

-- to count number of hotels --
select count(distinct(hotel_id)) from hotel;

select * from OYOHOTEL;
alter table OYOHOTEL
add column no_of_days_stayed int;
update OYOHOTEL set no_of_days_stayed= datediff(check_out,check_in);
-- number of cities in the data--
select count(distinct(city)) from OYOHOTEL;
-- to count hotels in per city --
select count(distinct(hotel_id)), city  from OYOHOTEL
group by city ;
-- Average room rate by per city--
alter table OYOHOTEL
add column rate float;
update OYOHOTEL set rate= round(((amount/no_of_days_stayed)/no_of_rooms),2);
select* from OYOHOTEL;
select round((avg(rate)),2) as avg_rate, city  from OYOHOTEL
group by city;

select count(status = "Cancelled") , city from OYOHOTEL as cancelled
group by city;
select count(booking_id),city from OYOHOTEL as bookings
group by city;
-- cancellation rate city wise--
alter table OYOHOTEL 
add column cancellation_rate float;
((select count(booking_id),city from OYOHOTEL
group by city)/( select count(status = "Cancelled") , city from OYOHOTEL
group by city));
-- number of nights stayed by customer--
select avg(no_of_days_stayed) from OYOHOTEL;

-- average discount offered city wise--
select avg(discount) from OYOHOTEL
group by city;

-- number of bookings in a given period of time--
-- bookings in january 15-30 in different cities--
select count(booking_id) as number_of_bookings ,city from OYOHOTEL
where check_in between '2017-01-15' and '2017-01-30'
group by city;

-- how many days prior bookings are made --

alter table OYOHOTEL 
add column prior_days int;
update OYOHOTEL set prior_days = datediff(check_in,date_of_booking);
select prior_days from OYOHOTEL;
-- TO SHOW AVERAGE NUMBER OF PRIOR DAYS BOOKING HAS BEEN MADE--
SELECT round(avg(prior_days),0) from OYOHOTEL;

-- revenue generated by the hoteks in the given time--

select sum((no_of_rooms)*(amount)) as revenue from OYOHOTEL;





